"""README draft generator."""

from __future__ import annotations

from pathlib import Path

from .analyzer import AnalysisResult
from .utils import write_text


class DocumentationGenerator:
    """Generate a concise README draft based on repository analysis."""

    def __init__(self, result: AnalysisResult) -> None:
        self.result = result

    def generate(self, output_dir: Path) -> Path:
        entry = self.result.entry_file or "run.py"
        modules = "\n".join(f"- `{module}`" for module in self.result.core_modules[:8]) or "- No Python module detected"
        content = f"""# Generated Project README

## Project Overview

This README draft was generated by RepoMind Agent. The analyzed repository contains **{self.result.total_files}** files, including **{self.result.python_files}** Python files and **{self.result.markdown_files}** Markdown documents.

## Entry Point

Detected entry file:

```bash
python {entry}
```

## Core Modules

{modules}

## Setup

```bash
pip install -r requirements.txt
```

## Usage

```bash
python {entry}
```

## Maintenance Notes

- Review generated quality report before merging code changes.
- Move hard-coded paths into configuration files.
- Add docstrings for public functions and classes.
- Keep README, tests and dependency files updated together.
"""
        return write_text(output_dir / "README_generated.md", content)
