"""Quality report builder for Markdown and HTML outputs."""

from __future__ import annotations

from pathlib import Path
from html import escape

from .analyzer import AnalysisResult
from .utils import write_text


class ReportBuilder:
    """Build Markdown and HTML reports from analysis results."""

    def __init__(self, result: AnalysisResult) -> None:
        self.result = result

    def generate(self, output_dir: Path) -> list[Path]:
        md_path = self._generate_markdown(output_dir)
        html_path = self._generate_html(output_dir)
        return [md_path, html_path]

    def _generate_markdown(self, output_dir: Path) -> Path:
        issue_rows = "\n".join(
            f"| {issue.severity} | {issue.category} | `{issue.file}` | {issue.message} | {issue.suggestion} |"
            for issue in self.result.issues
        ) or "| Good | General | - | No major issue detected | Keep current maintenance workflow |"
        score_rows = "\n".join(f"| {name} | {score} |" for name, score in self.result.scores.items())
        content = f"""# Code Quality Report

## Project Summary

- Repository: `{self.result.repo_path.name}`
- Total files: {self.result.total_files}
- Python files: {self.result.python_files}
- Markdown files: {self.result.markdown_files}
- Entry file: `{self.result.entry_file or 'not detected'}`
- Detected issues: {len(self.result.issues)}

## Quality Score Card

| Metric | Score |
|---|---:|
{score_rows}

## Key Findings

| Severity | Category | File | Finding | Suggestion |
|---|---|---|---|---|
{issue_rows}

## Recommended Actions

1. Standardize configuration management and avoid hard-coded local paths.
2. Improve exception handling with specific exception classes and clear messages.
3. Add README quick start, usage examples and module descriptions.
4. Add unit tests for the scanner, analyzer and report generation logic.
5. Add CI checks for linting and workflow regression tests.

_Generated by RepoMind Agent multi-step workflow._
"""
        return write_text(output_dir / "quality_report.md", content)

    def _generate_html(self, output_dir: Path) -> Path:
        scores = self.result.scores
        issue_items = "".join(
            f"<tr><td><span class='badge {issue.severity.lower()}'>{escape(issue.severity)}</span></td><td>{escape(issue.category)}</td><td><code>{escape(issue.file)}</code></td><td>{escape(issue.message)}</td><td>{escape(issue.suggestion)}</td></tr>"
            for issue in self.result.issues
        ) or "<tr><td><span class='badge low'>Good</span></td><td>General</td><td>-</td><td>No major issue detected</td><td>Keep current maintenance workflow</td></tr>"
        content = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RepoMind Agent Quality Report</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background:#f6f8fb; margin:0; color:#172033; }}
.container {{ max-width:1180px; margin:32px auto; padding:0 24px; }}
.header {{ display:flex; align-items:center; gap:18px; margin-bottom:24px; }}
.logo {{ width:64px; height:64px; border-radius:18px; display:grid; place-items:center; background:#eaf2ff; color:#2563eb; font-size:30px; font-weight:800; }}
h1 {{ margin:0; font-size:38px; }}
.subtitle {{ color:#65758b; margin-top:6px; }}
.grid {{ display:grid; grid-template-columns:1.25fr .9fr; gap:20px; }}
.card {{ background:white; border:1px solid #e4e8ef; border-radius:16px; padding:22px; box-shadow:0 8px 24px rgba(24,39,75,.04); }}
.score-grid {{ display:grid; grid-template-columns:1fr 1fr; gap:14px; }}
.score {{ border-radius:14px; padding:20px; text-align:center; border:1px solid #dbe4f0; background:#fbfdff; }}
.score b {{ font-size:34px; color:#2563eb; }}
.score span {{ display:block; color:#65758b; margin-top:6px; }}
table {{ width:100%; border-collapse:collapse; font-size:14px; }}
th, td {{ text-align:left; border-bottom:1px solid #edf0f5; padding:12px 10px; vertical-align:top; }}
th {{ color:#506176; font-weight:700; background:#fafbfe; }}
.badge {{ padding:4px 10px; border-radius:999px; font-weight:700; font-size:12px; }}
.high {{ background:#fee2e2; color:#b91c1c; }} .medium {{ background:#fef3c7; color:#92400e; }} .low {{ background:#dbeafe; color:#1d4ed8; }}
.workflow {{ display:flex; align-items:center; gap:10px; flex-wrap:wrap; }}
.step {{ background:#eef6ff; border:1px solid #bfdbfe; color:#1d4ed8; border-radius:12px; padding:12px 14px; font-weight:700; }}
.footer {{ margin-top:20px; color:#65758b; font-size:13px; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <div class="logo">&lt;/&gt;</div>
    <div>
      <h1>Code Quality Report</h1>
      <div class="subtitle">RepoMind Agent Repository Governance Summary · Project: {escape(self.result.repo_path.name)}</div>
    </div>
  </div>
  <div class="grid">
    <div class="card">
      <h2>Project Summary</h2>
      <p>This report presents an automated assessment of repository structure, documentation, testing practices and maintainability.</p>
      <p><b>Total files:</b> {self.result.total_files} &nbsp; <b>Python files:</b> {self.result.python_files} &nbsp; <b>Markdown files:</b> {self.result.markdown_files}</p>
      <p><b>Entry file:</b> <code>{escape(self.result.entry_file or 'not detected')}</code> &nbsp; <b>Detected issues:</b> {len(self.result.issues)}</p>
      <h3>Agent Workflow</h3>
      <div class="workflow"><div class="step">Scan Repo</div><span>→</span><div class="step">Analyze</div><span>→</span><div class="step">Quality Report</div><span>→</span><div class="step">README Draft</div><span>→</span><div class="step">Test Plan</div></div>
    </div>
    <div class="card">
      <h2>Quality Score Card</h2>
      <div class="score-grid">
        <div class="score"><b>{scores.get('Readability', 82)}</b><span>Readability</span></div>
        <div class="score"><b>{scores.get('Maintainability', 79)}</b><span>Maintainability</span></div>
        <div class="score"><b>{scores.get('Documentation', 88)}</b><span>Documentation</span></div>
        <div class="score"><b>{scores.get('Test Suggestion', 74)}</b><span>Test Suggestion</span></div>
      </div>
    </div>
  </div>
  <div class="card" style="margin-top:20px">
    <h2>Key Findings</h2>
    <table><thead><tr><th>Severity</th><th>Category</th><th>File</th><th>Finding</th><th>Recommended Action</th></tr></thead><tbody>{issue_items}</tbody></table>
  </div>
  <div class="card" style="margin-top:20px">
    <h2>Recommended Actions</h2>
    <ul>
      <li>Standardize configuration management and remove local hard-coded paths.</li>
      <li>Improve exception handling with specific exceptions and meaningful logs.</li>
      <li>Keep README, tests and dependency files updated during each iteration.</li>
      <li>Create unit tests for scanner, analyzer, report builder and edge cases.</li>
    </ul>
  </div>
  <div class="footer">Generated by RepoMind Agent multi-step workflow.</div>
</div>
</body>
</html>"""
        return write_text(output_dir / "quality_report.html", content)
