"""Test plan generator."""

from __future__ import annotations

from pathlib import Path

from .analyzer import AnalysisResult
from .utils import write_text


class TestPlanner:
    """Generate practical unit-test suggestions for the scanned repository."""

    def __init__(self, result: AnalysisResult) -> None:
        self.result = result

    def generate(self, output_dir: Path) -> Path:
        modules = self.result.core_modules[:8]
        module_items = "\n".join(f"- Add unit tests for `{module}`: normal input, empty input, invalid path and boundary cases." for module in modules)
        if not module_items:
            module_items = "- Add unit tests after core modules are created."
        content = f"""# Test Plan Generated by RepoMind Agent

## Test Scope

The repository currently includes **{len(self.result.test_files)}** detected test files. Suggested focus areas:

{module_items}

## Recommended Test Categories

1. **Parser tests**: verify command-line arguments and default values.
2. **Repository scanning tests**: verify file counting, ignored directories and entry detection.
3. **Issue detection tests**: verify hard-coded path, broad exception and missing README checks.
4. **Report generation tests**: verify Markdown/HTML files are created in the output directory.
5. **Regression tests**: keep sample repositories for repeated workflow validation.

## Suggested Commands

```bash
python run.py --repo ./demo_repo --output ./outputs --with-doc --with-report --with-tests
```
"""
        return write_text(output_dir / "test_plan.md", content)
